
version: '3.1'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # network_mode: host
    ports:
      - 5432:5432
    volumes:
      - queue_test_db:/var/lib/postgresql

  adminer:
    image: adminer
    # network_mode: host
    ports:
      - 8085:8080

volumes:
  queue_test_db:
